name: Buildroot and br_dpdk Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'

jobs:
  br_build:
    name: Buildroot setup and build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the br_dpdk repository
      uses: actions/checkout@v4
      with:
        repository: 'vjardin/br_dpdk'
        path: 'br_dpdk'

    - name: Checkout GitLab's Buildroot using the github mirror
      uses: actions/checkout@v4
      with:
        repository: 'buildroot/buildroot'
        ref: 'master'
        path: 'br'
        fetch-depth: 1  # Fetch only the latest commit to save time

    - name: Check available cores
      run: |
        nproc --all

    - name: Install build dependencies
      uses: ConorMacBride/install-package@v1
      with:
        apt: |
          git \
          wget \
          cpio \
          unzip \
          rsync \
          bc \
          file \
          bison \
          yacc \
          flex \
          texinfo \
          python3 \
          python3-aiohttp \
          python3-distutils-extra \
          python3-flake8 \
          build-essential \
          qemu-system-x86 \
          qemu-utils

    - name: Configure Buildroot for QEMU x86_64
      run: |
        cd br
        BR2_DL_DIR=../br_dl make BR2_EXTERNAL=../br_dpdk O=../br_output qemu_x86_64_defconfig

    - name: Set the Buildroot .config
      run: |
        cd br
        cat > ../br_output/.config <<- 'EOFCONFIG'
          BR2_x86_64=y
          BR2_x86_nehalem=y
          BR2_ROOTFS_POST_BUILD_SCRIPT="board/qemu/x86_64/post-build.sh"
          BR2_ROOTFS_POST_IMAGE_SCRIPT="board/qemu/post-image.sh"
          BR2_ROOTFS_POST_SCRIPT_ARGS="qemu_x86_64_defconfig"
          BR2_LINUX_KERNEL=y
          BR2_LINUX_KERNEL_USE_CUSTOM_CONFIG=y
          BR2_LINUX_KERNEL_CUSTOM_CONFIG_FILE="board/qemu/x86_64/linux.config"
          BR2_LINUX_KERNEL_NEEDS_HOST_LIBELF=y
          BR2_PACKAGE_DPDK=y
          BR2_PACKAGE_LIBBPF=y
          BR2_PACKAGE_RDMA_CORE=y
          BR2_PACKAGE_OPENSSL=y
          BR2_PACKAGE_DTC=y
          BR2_PACKAGE_JANSSON=y
          BR2_PACKAGE_LIBPCAP=y
          BR2_PACKAGE_NUMACTL=y
          BR2_TARGET_ROOTFS_EXT2=y
          BR2_TARGET_ROOTFS_EXT2_SIZE="200M"
          # BR2_TARGET_ROOTFS_TAR is not set
        EOFCONFIG
        BR2_DL_DIR=../br_dl make BR2_EXTERNAL=../br_dpdk O=../br_output olddefconfig

    - name: Compile Buildroot and br_dpdk package
      run: |
        cd br
        BR2_DL_DIR=../br_dl make BR2_EXTERNAL=../br_dpdk O=../br_output -j$(nproc --all)

    - name: legal info of Buildroot and br_dpdk package
      run: |
        cd br
        BR2_DL_DIR=../br_dl make BR2_EXTERNAL=../br_dpdk O=../br_output legal-info

    - name: pkg-stats of Buildroot and br_dpdk package
      run: |
        cd br
        BR2_DL_DIR=../br_dl make BR2_EXTERNAL=../br_dpdk O=../br_output pkg-stats

    - name: check-package of br_dpdk
      run: |
        cd br
        utils/check-package -b  ../br_dpdk/package/dpdk/*

    - name: test-pkg for br_dpdk (1h+)
      run: |
        cd br
        BR2_DL_DIR=../br_dl BR2_EXTERNAL=../br_dpdk utils/test-pkg -a -p dpdk
